CC=gcc
ERROR=-w

all:14 15 book18 book19 book20 book21 book22

14:book14.c
	$(CC) $(ERROR) -o 14 book14.c 

15:book15.c
	$(CC) -o 15 book15.c
book18:book18.c
	g++ book18.c -o book18

book19:book19.cpp
	g++  $(ERROR) book19.cpp -o book19
book20:book20.cpp
	g++  $(ERROR) book20.cpp -o book20
book21:book21.cpp
	g++  $(ERROR) book21.cpp -o book21
book22:book22.cpp
	g++  $(ERROR) book22.cpp -o book22

clean:
	rm -f 14 15 book18 book19 book20 book21 book22
	

  
